"""Rename one column

Revision ID: 00b6de24186e
Revises: 12a47c8cad9b
Create Date: 2024-08-20 19:19:09.548433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b6de24186e'
down_revision: Union[str, None] = '12a47c8cad9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
