"""Configure cascade delete

Revision ID: 5b8db3bf9f44
Revises: 849ed5420d33
Create Date: 2024-08-01 20:07:13.705178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8db3bf9f44'
down_revision: Union[str, None] = '849ed5420d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_report_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('images_report_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reports_user_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('stars_user_id_fkey', 'stars', type_='foreignkey')
    op.drop_constraint('stars_report_id_fkey', 'stars', type_='foreignkey')
    op.create_foreign_key(None, 'stars', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stars', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stars', type_='foreignkey')
    op.drop_constraint(None, 'stars', type_='foreignkey')
    op.create_foreign_key('stars_report_id_fkey', 'stars', 'reports', ['report_id'], ['id'])
    op.create_foreign_key('stars_user_id_fkey', 'stars', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_user_id_fkey', 'reports', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_report_id_fkey', 'images', 'reports', ['report_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_report_id_fkey', 'comments', 'reports', ['report_id'], ['id'])
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
