"""Update all models

Revision ID: 83849df4de88
Revises: a4528d005def
Create Date: 2025-02-10 15:42:53.545169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83849df4de88'
down_revision: Union[str, None] = 'a4528d005def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_constraint('users_short_name_key', 'users', type_='unique')
    op.drop_column('users', 'short_name')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('user', 'admin', name='roles'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_short_name_key', 'users', ['short_name'])
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
