"""FIX

Revision ID: d4fb4583beab
Revises: 5b8db3bf9f44
Create Date: 2024-08-01 20:11:03.187117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fb4583beab'
down_revision: Union[str, None] = '5b8db3bf9f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('caught_fish_report_id_fkey', 'caught_fish', type_='foreignkey')
    op.create_foreign_key(None, 'caught_fish', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'caught_fish', type_='foreignkey')
    op.create_foreign_key('caught_fish_report_id_fkey', 'caught_fish', 'reports', ['report_id'], ['id'])
    # ### end Alembic commands ###
